const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
const ADD_TO_CART = 'ADD_TO_CART';
const ADD_SUCCESS = 'ADD_SUCCESS';
const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export default {
  FETCH_PRODUCTS_REQUEST,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_ERROR,
  FETCH_PRODUCT_REQUEST,
  FETCH_PRODUCT_ERROR,
  ADD_TO_CART,
  ADD_SUCCESS,
  FETCH_CATEGORIES,
};
